### PR TITLE
Added Displaying images

### PR DESCRIPTION
**Pull request by shinokada**
I assumed that [this](http://forum.asgardcms.com/topic/149/how-add-image-on-theme/2) is correct and added to [theme doc](https://asgardcms.com/docs/v1/themes/usage). Please have a look at it.

### CODE REVIEW

**Comment by nWidart** [comment]
Hello,

Thank you for your contribution.
I spotted a typo "Assuiming" instead of "Assuming"

In the same way it might be a good idea to add how to add a stylesheet / javascript file. Which is done by using `Theme::style()` and `Theme::script()` respectively.

**Comment by shinokada** [comment]
Ok I will update it now.

**Comment by shinokada** [comment]
Well you already have them in your document though.

```
Linking to theme assets
To link to a theme asset you can use the following helpers:
{!! Theme::style('css/vendor/bootstrap.min.css') !!}

{!! Theme::script('js/vendor/jquery.min.js') !!}
```

**Comment by shinokada** [comment]
Is there any other methods you can add using `Theme::method`? Which file tells us all the methods for `Theme`?

**Comment by nWidart** [comment]
Why did you update the same typo 3 times ?

**Comment by nWidart** [comment]
The reason I didn't add this in the docs is because it's part of the Stylist package documentation, you can find all methods there.

**Comment by shinokada** [comment]
What is the url of Stylist package documentation?

**Comment by nWidart** [comment]
It's on the documentation of asgardcms... https://github.com/floatingpointsoftware/stylist

**Pull request closed without merging**
